name: bmi_calculator
description: A BMI calculator app developed with Flutter.
publish_to: 'none'
version: 3.3.0

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_svg: ^2.0.2
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.0.3
  intl: ^0.18.0
  shared_preferences: ^2.0.7

dev_dependencies:
  build_runner: ^2.3.0
  dart_code_metrics: ^5.6.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  test: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
